#!/usr/bin/env python

# Make the directory etc. for my next Project Euler problem

import glob
import os

probs = set(glob.glob("./[0-9][0-9][0-9]/"))
assert probs == set(["./" + str(i+1).zfill(3) + "/" for i in range(len(probs))])

next = len(probs) + 1

# 3-digit number for problem
num_str = str(next).zfill(3)

# make new directory
os.mkdir(num_str)

# make new C++ source file
with open(os.path.join(num_str, num_str + ".cpp"), "w") as cpp:
	cpp.write("// \n\n#include <iostream>\n")
	cpp.write("\nint main()\n{\n\t\n\t\n\treturn 0;\n}")

# write the new makefile
with open(os.path.join(num_str, "Makefile"), "w") as make:
	make.write("%s: %s.cpp\n\tg++ %s.cpp -o %s\n" % tuple([num_str] * 4))
	make.write("\n.PHONY: clean\n\nclean:\n\trm -f %s\n" % (num_str,))

# print message to the user
print "Prepared the directory for Problem %d!" % (next)

